generate_trie_utils = executable(
    'generate_trie', ['generate_trie.c'],
    include_directories : includes,
    link_with : libccittfax,
    install : false)

mkbmp_utils = executable(
    'mkbmp', ['mkbmp.c'],
    include_directories : includes,
    link_with : libccittfax,
    install : false)
